title: MZ_Visualization.jl
description: This is the documentation website for the package MZ_Visulaization.jl
theme: just-the-docs

url: https://EMCMS.github.io/MZ_Visualization_docs

aux_links:
  Template Repository: https://EMCMS.github.io/MZ_Visualization_docs
